# Generated by Django 5.2.10 on 2026-01-11 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0006_add_session_consumption_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sandboxartifact',
            new_name='sandbox_san_session_03337c_idx',
            old_name='sandbox_art_session_idx',
        ),
        migrations.RenameIndex(
            model_name='sandboxsession',
            new_name='sandbox_san_status_eb5de5_idx',
            old_name='sandbox_ses_status_idx',
        ),
        migrations.RenameIndex(
            model_name='sandboxsession',
            new_name='sandbox_san_mode_2f8d9e_idx',
            old_name='sandbox_ses_mode_idx',
        ),
        migrations.RenameIndex(
            model_name='sandboxsnapshot',
            new_name='sandbox_san_session_61ad75_idx',
            old_name='sandbox_snap_session_idx',
        ),
    ]
