"""Base executor implementations and helper utilities."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from astraforge.domain.models.request import ChangeSet, ExecutionPlan, PlanStep, Request
from astraforge.domain.providers.interfaces import AgentExecutor


@dataclass
class StaticPlanExecutor(AgentExecutor):
    """Fallback executor used for local testing; produces canned plans and diffs."""

    name: str = "static"

    def plan(self, request: Request) -> ExecutionPlan:
        steps = [
            PlanStep(description="Collect repository context"),
            PlanStep(description=f"Implement request: {request.payload.title}"),
        ]
        return ExecutionPlan(steps=steps, summary="Autogenerated static plan")

    def apply(self, plan: ExecutionPlan, repository: str, workspace: str) -> ChangeSet:
        reports = {step.description: "completed" for step in plan.steps}
        return ChangeSet(
            diff_uri=f"artifact://{repository}/{workspace}/diff.patch", reports=reports
        )


@dataclass
class DelegatingExecutor(AgentExecutor):
    """Thin wrapper that delegates to an external LLM-powered executor via SDK."""

    name: str
    client: Any

    def plan(
        self, request: Request
    ) -> ExecutionPlan:  # pragma: no cover - network call placeholder
        response = self.client.plan(request)
        return ExecutionPlan(
            steps=[PlanStep(description=s) for s in response.steps],
            summary=response.summary,
        )

    def apply(
        self, plan: ExecutionPlan, repository: str, workspace: str
    ) -> ChangeSet:  # pragma: no cover
        response = self.client.apply(
            plan=plan, repository=repository, workspace=workspace
        )
        return ChangeSet(diff_uri=response.diff_uri, reports=response.reports)
