# Generated by Django 5.2.10 on 2026-01-11 23:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_use', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='computeruserun',
            new_name='computer_us_status_f1a78f_idx',
            old_name='computer_use_status_idx',
        ),
        migrations.RenameIndex(
            model_name='computeruserun',
            new_name='computer_us_created_accb12_idx',
            old_name='computer_use_created_idx',
        ),
        migrations.AddField(
            model_name='computeruserun',
            name='final_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='computeruserun',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
