# Generated by Django 5.2.10 on 2026-01-11 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_workspace_plan_and_quota_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
