# Generated by Django 5.2.10 on 2026-01-11 23:07

import astraforge.quotas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacequotaledger',
            name='period_start',
            field=models.DateField(default=astraforge.quotas.models._month_start),
        ),
    ]
