import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { DiffPreview } from "@/components/diff-preview";

const sampleMergeRequests = [
  {
    id: "mr-101",
    title: "feat: add retry logic",
    branch: "feature/retry-logic",
    url: "https://gitlab.example.com/org/repo/-/merge_requests/101",
    status: "OPEN"
  }
];

export default function MergeRequestsPage() {
  return (
    <div className="mx-auto flex max-w-4xl flex-col gap-4 p-6">
      <header className="space-y-1">
        <h1 className="text-xl font-semibold">Merge Requests</h1>
        <p className="text-sm text-muted-foreground">Track MRs generated by AstraForge.</p>
      </header>
      {sampleMergeRequests.map((mr) => (
        <Card key={mr.id}>
          <CardHeader>
            <CardTitle>{mr.title}</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            <div className="text-sm">Branch: {mr.branch}</div>
            <div className="text-sm">Status: {mr.status}</div>
            <DiffPreview diff={`--- a/file
+++ b/file
`} />
            <a className="text-sm text-primary underline" href={mr.url} target="_blank" rel="noreferrer">
              Open in VCS
            </a>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}
