# Generated by Django 5.2.7 on 2025-10-22 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("gitlab", "GitLab"), ("github", "GitHub")],
                        max_length=20,
                    ),
                ),
                ("repository", models.CharField(max_length=255)),
                ("access_token", models.TextField()),
                ("base_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repository_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Repository Link",
                "verbose_name_plural": "Repository Links",
                "ordering": ["created_at"],
                "unique_together": {("user", "provider", "repository")},
            },
        ),
    ]
