# Generated by Django 5.2.10 on 2026-01-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astracontrolsession',
            name='last_snapshot_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
