# Generated by Django 5.2.10 on 2026-01-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra_control', '0002_astracontrolsession_last_snapshot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astracontrolsession',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='created', max_length=20),
        ),
    ]
